apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: witness-it-doppler-secret-prod
  namespace: default
spec:
  tokenSecret:
    name: witness-it-doppler-token-prod
  managedSecret:
    name: witness-it-secret-prod
    namespace: default
  resyncSeconds: 10
