apiVersion: v1
kind: Secret
metadata:
  name: witness-it-doppler-token-prod
  namespace: default
type: Opaque
data:
  serviceToken: ZHAuc3QucHJkLmdaM0lhV0d3a3Zvc0FjODhtNlYxdXNOQlVCaGJBcmFtd3BEWXFzQVJtV0UK
